service: algorewriter
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-3
  memorySize: 128
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
